// generated by gen-tuple.ts

package io.github.leawind.inventory.tuple;

public final class Tuple {
  private Tuple() {}

  public record Tuple1<T1>(T1 v1) {}

  public record Tuple2<T1, T2>(T1 v1, T2 v2) {}

  public record Tuple3<T1, T2, T3>(T1 v1, T2 v2, T3 v3) {}

  public record Tuple4<T1, T2, T3, T4>(T1 v1, T2 v2, T3 v3, T4 v4) {}

  public record Tuple5<T1, T2, T3, T4, T5>(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5) {}

  public record Tuple6<T1, T2, T3, T4, T5, T6>(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6) {}

  public record Tuple7<T1, T2, T3, T4, T5, T6, T7>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7) {}

  public record Tuple8<T1, T2, T3, T4, T5, T6, T7, T8>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8) {}

  public record Tuple9<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9) {}

  public record Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10) {}

  public record Tuple11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11) {}

  public record Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12) {}

  public record Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
      T1 v1,
      T2 v2,
      T3 v3,
      T4 v4,
      T5 v5,
      T6 v6,
      T7 v7,
      T8 v8,
      T9 v9,
      T10 v10,
      T11 v11,
      T12 v12,
      T13 v13) {}

  public record Tuple14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
      T1 v1,
      T2 v2,
      T3 v3,
      T4 v4,
      T5 v5,
      T6 v6,
      T7 v7,
      T8 v8,
      T9 v9,
      T10 v10,
      T11 v11,
      T12 v12,
      T13 v13,
      T14 v14) {}

  public record Tuple15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
      T1 v1,
      T2 v2,
      T3 v3,
      T4 v4,
      T5 v5,
      T6 v6,
      T7 v7,
      T8 v8,
      T9 v9,
      T10 v10,
      T11 v11,
      T12 v12,
      T13 v13,
      T14 v14,
      T15 v15) {}

  public record Tuple16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(
      T1 v1,
      T2 v2,
      T3 v3,
      T4 v4,
      T5 v5,
      T6 v6,
      T7 v7,
      T8 v8,
      T9 v9,
      T10 v10,
      T11 v11,
      T12 v12,
      T13 v13,
      T14 v14,
      T15 v15,
      T16 v16) {}

  public static <T1> Tuple1<T1> of(T1 v1) {
    return new Tuple1<>(v1);
  }

  public static <T1, T2> Tuple2<T1, T2> of(T1 v1, T2 v2) {
    return new Tuple2<>(v1, v2);
  }

  public static <T1, T2, T3> Tuple3<T1, T2, T3> of(T1 v1, T2 v2, T3 v3) {
    return new Tuple3<>(v1, v2, v3);
  }

  public static <T1, T2, T3, T4> Tuple4<T1, T2, T3, T4> of(T1 v1, T2 v2, T3 v3, T4 v4) {
    return new Tuple4<>(v1, v2, v3, v4);
  }

  public static <T1, T2, T3, T4, T5> Tuple5<T1, T2, T3, T4, T5> of(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5) {
    return new Tuple5<>(v1, v2, v3, v4, v5);
  }

  public static <T1, T2, T3, T4, T5, T6> Tuple6<T1, T2, T3, T4, T5, T6> of(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6) {
    return new Tuple6<>(v1, v2, v3, v4, v5, v6);
  }

  public static <T1, T2, T3, T4, T5, T6, T7> Tuple7<T1, T2, T3, T4, T5, T6, T7> of(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7) {
    return new Tuple7<>(v1, v2, v3, v4, v5, v6, v7);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8> Tuple8<T1, T2, T3, T4, T5, T6, T7, T8> of(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8) {
    return new Tuple8<>(v1, v2, v3, v4, v5, v6, v7, v8);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9> Tuple9<T1, T2, T3, T4, T5, T6, T7, T8, T9> of(
      T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9) {
    return new Tuple9<>(v1, v2, v3, v4, v5, v6, v7, v8, v9);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>
      Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> of(
          T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10) {
    return new Tuple10<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>
      Tuple11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> of(
          T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11) {
    return new Tuple11<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>
      Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> of(
          T1 v1,
          T2 v2,
          T3 v3,
          T4 v4,
          T5 v5,
          T6 v6,
          T7 v7,
          T8 v8,
          T9 v9,
          T10 v10,
          T11 v11,
          T12 v12) {
    return new Tuple12<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>
      Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> of(
          T1 v1,
          T2 v2,
          T3 v3,
          T4 v4,
          T5 v5,
          T6 v6,
          T7 v7,
          T8 v8,
          T9 v9,
          T10 v10,
          T11 v11,
          T12 v12,
          T13 v13) {
    return new Tuple13<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>
      Tuple14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> of(
          T1 v1,
          T2 v2,
          T3 v3,
          T4 v4,
          T5 v5,
          T6 v6,
          T7 v7,
          T8 v8,
          T9 v9,
          T10 v10,
          T11 v11,
          T12 v12,
          T13 v13,
          T14 v14) {
    return new Tuple14<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>
      Tuple15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> of(
          T1 v1,
          T2 v2,
          T3 v3,
          T4 v4,
          T5 v5,
          T6 v6,
          T7 v7,
          T8 v8,
          T9 v9,
          T10 v10,
          T11 v11,
          T12 v12,
          T13 v13,
          T14 v14,
          T15 v15) {
    return new Tuple15<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15);
  }

  public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>
      Tuple16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> of(
          T1 v1,
          T2 v2,
          T3 v3,
          T4 v4,
          T5 v5,
          T6 v6,
          T7 v7,
          T8 v8,
          T9 v9,
          T10 v10,
          T11 v11,
          T12 v12,
          T13 v13,
          T14 v14,
          T15 v15,
          T16 v16) {
    return new Tuple16<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16);
  }
}
