const PACKAGE = "io.github.leawind.inventory.tuple";
const JAVA_FILE =
	"lib/src/main/java/io/github/leawind/inventory/tuple/Tuple.java";

const MAX = 32;

function main() {
	const nums = Array
		.from({ length: MAX + 1 }, (_, i) => i);

	const argNames = nums.map((i) => `$${i}`);

	const lines = [
		`// generated by gen-tuple.ts`,
		``,
		`package ${PACKAGE};`,
		``,
		``,
		`public final class Tuple {`,

		...nums.map((i) => `  public record _${i}${types(i)}(${params(i)}){}`),

		...nums.map((i) =>
			[
				`  public static ` +
				`${types(i)} _${i}${types(i)} of(${params(i)}) {`,
				`    return new _${i}${i === 0 ? "" : "<>"}(${args(i)});`,
				`  }`,
			].join("\n")
		),
		`}`,
	];

	Deno.writeTextFileSync(JAVA_FILE, lines.join("\n"));

	function types(i: number) {
		const typeNames = nums.slice(0, i)
			.map((j) => `T${j}`)
			.join(", ");
		return i === 0 ? "" : `<${typeNames}>`;
	}

	function params(i: number) {
		return nums.slice(0, i)
			.map((j) => `T${j} ${argNames[j]}`)
			.join(", ");
	}

	function args(i: number) {
		return nums.slice(0, i)
			.map((j) => argNames[j])
			.join(", ");
	}
}

if (import.meta.main) {
	main();
}
